"""Generate extractor/src/tables.rs from pdfminer.six's copies of the PDF spec tables.

- Standard, MacRoman and WinAnsi encodings (ISO 32000-1 Annex D), from pdfminer/latin_enc.py.
- The Adobe Glyph List (glyph name -> Unicode), from pdfminer/glyphlist.py.
- The widths of the 14 standard fonts (Adobe AFM files), from pdfminer/fontmetrics.py.
- The 258 standard Macintosh glyph names, from fontTools (MIT).

Run: python tools/gen_tables.py > extractor/src/tables.rs
The output is committed, so building never needs Python.
"""
import sys
from pdfminer.latin_enc import ENCODING
from pdfminer.glyphlist import glyphname2unicode
from pdfminer.fontmetrics import FONT_METRICS


def rust_str(s):
    return '"' + ''.join(c if (32 <= ord(c) < 127 and c not in '"\\') else '\\u{%x}' % ord(c) for c in s) + '"'


def base_table(col):
    codes = [0] * 256
    for row in ENCODING:
        name, code = row[0], row[col]
        if code is None:
            continue
        u = glyphname2unicode.get(name)
        if u is None or len(u) != 1:
            sys.exit(f'no single code point for {name}')
        codes[code] = ord(u)
    return codes


out = sys.stdout
out.write('//! Generated by tools/gen_tables.py. Do not edit by hand.\n//!\n')
out.write('//! The encodings are from ISO 32000-1 Annex D. The glyph list and the standard-font widths are\n')
out.write('//! Adobe data, used under this notice:\n//!\n')
out.write('//! Copyright (c) 1997, 1998, 2002, 2007, 2010 Adobe Systems Incorporated. Permission is hereby granted,\n')
out.write('//! free of charge, to any person obtaining a copy of this documentation file to use, copy, publish,\n')
out.write('//! distribute, sublicense, and/or sell copies of the documentation, and to permit others to do the same,\n')
out.write('//! provided that no modification is made and that the above copyright notice and this permission notice\n')
out.write('//! are included in all copies. (Adobe Glyph List and AFM files, via pdfminer.six.)\n\n')

for label, col in (('STANDARD', 1), ('MAC_ROMAN', 2), ('WIN_ANSI', 3)):
    t = base_table(col)
    out.write(f'/// {label} encoding: code -> Unicode scalar (0 = no glyph).\n')
    out.write(f'pub static {label}: [u16; 256] = [\n')
    for i in range(0, 256, 16):
        out.write('    ' + ', '.join(f'0x{c:04x}' for c in t[i:i + 16]) + ',\n')
    out.write('];\n\n')

names = sorted(glyphname2unicode.items())
out.write('/// Adobe Glyph List, sorted by name for binary search.\n')
out.write(f'pub static AGL: [(&str, &str); {len(names)}] = [\n')
for n, u in names:
    out.write(f'    ({rust_str(n)}, {rust_str(u)}),\n')
out.write('];\n\n')

out.write('/// Widths of the 14 standard fonts, per character, in 1/1000 em. Sorted by font name.\n')
fonts = sorted(FONT_METRICS.items())
out.write(f'pub static STANDARD_WIDTHS: [(&str, &[(char, u16)]); {len(fonts)}] = [\n')
for fname, (desc, widths) in fonts:
    pairs = sorted((ord(c), w) for c, w in widths.items() if len(c) == 1)
    body = ', '.join(f"('\\u{{{c:x}}}', {int(w)})" for c, w in pairs)
    out.write(f'    ({rust_str(fname)}, &[{body}]),\n')
out.write('];\n')

# The 258 standard Macintosh glyph names, which TrueType 'post' tables (formats 1 and 2) index into.
from fontTools.ttLib.standardGlyphOrder import standardGlyphOrder
out.write('\n/// The 258 standard Macintosh glyph names used by TrueType post tables (via fontTools).\n')
out.write(f'pub static MAC_GLYPHS: [&str; {len(standardGlyphOrder)}] = [\n')
for i in range(0, len(standardGlyphOrder), 8):
    out.write('    ' + ', '.join(rust_str(n) for n in standardGlyphOrder[i:i + 8]) + ',\n')
out.write('];\n')
